import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Inter font update
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Navbar from "@/components/shared/Navbar";
import CustomCursor from "@/components/shared/CustomCursor";
import { ThemeProvider } from "@/providers/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">

        {/* theme provider */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* custom cursor */}
          <CustomCursor />

          {/* navbar */}
          <Navbar />

          {/* main */}
          <main className="pt-20">
            {children}
          </main>
        </ThemeProvider>

      </body>
    </html>
  );
}
