export const Allprojects = [
  {
    id: "2",
    title: "Fashion Museum BD",
    description: "A premium fashion retail solution focusing on high-quality visual presentation and user engagement.",
    image: "/fashionmuseum_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://fashionmuseumbd.com/",
    technologies: ["Next.js", "React", "Tailwind CSS", "Vercel", "MUI", "Framer Motion"],
  },
  {
    id: "7",
    title: "ChatsNest",
    description: "A real-time instant messaging application featuring seamless room-based communication and live interaction using WebSockets.",
    image: "/chatsnest_mockup.png", // actual path check kore nio
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://chatsnest.vercel.app/",
    technologies: ["Next.js", "Socket.io", "Express.js", "Tailwind CSS"],
  },
  {
    id: "3",
    title: "Ibrahim Mahmud Portfolio",
    description: "A professional digital strategist portfolio showcasing services, results, and expertise with sleek animations.",
    image: "/ibrahim_portfolio_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://ibrahimmahmud.com/",
    technologies: ["Next.js", "Framer Motion", "Tailwind", "Lucide Icons"],
  },
  {
    id: "4",
    title: "Automation Section",
    description: "A specialized automation landing page demonstrating high-speed processing and modern interface logic.",
    image: "/automation_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://next-js-la-section-automation.vercel.app/",
    technologies: ["Next.js", "TypeScript", "GSAP", "Server Components"],
  },
  {
    id: "5",
    title: "Halal Market BD",
    description: "A niche e-commerce marketplace focused on halal-certified products with secure payment integration.",
    image: "/halalmarket_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://halalmarketbd.com/",
    technologies: ["React", "Node.js", "MongoDB", "Payment Gateway"],
  },
  {
    id: "6",
    title: "FlexShip IT",
    description: "Official agency website for FlexShip IT, highlighting high-performance software engineering and digital solutions.",
    image: "/flexship_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://flexship-it.vercel.app/",
    technologies: ["Next.js", "Tailwind", "Shadcn UI", "Agency Site"],
  },
  {
    id: "1",
    title: "FairBazar",
    description: "A comprehensive e-commerce platform designed for seamless shopping experiences with a clean, modern UI.",
    image: "/fairbazar_mockup.png", // Update with your actual screenshot path
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://fairbazar.vercel.app/",
    technologies: ["Next.js", "Tailwind CSS", "Redux", "Node.js"],
  },
  {
    id: "8",
    title: "Rongchowa",
    description: "A visually stunning creative landing page featuring high-end animations and a seamless full-stack integration for lead management.",
    image: "/rongchowa_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://rongchowa.vercel.app/",
    technologies: ["React", "Framer Motion", "Node.js", "MongoDB"],
  },
  {
    id: "9",
    title: "SubashStyle",
    description: "A luxury fragrance landing page designed with elegant transitions and a robust full-stack architecture for a premium shopping experience.",
    image: "/subashstyle_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://subashstyle-com.vercel.app/",
    technologies: ["React", "Framer Motion", "Node.js", "MongoDB"],
  },
  {
    id: "10",
    title: "MOAS-DB",
    description: "A high-conversion educational landing page built with interactive course modules and a seamless full-stack backend for student enrollment.",
    image: "/moas_db_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://moas-db.vercel.app/",
    technologies: ["React", "Framer Motion", "Node.js", "MongoDB"],
  },
  {
    id: "11",
    title: "AssetVerse Pro",
    description: "An enterprise-level Asset & Employee Management System featuring automated tracking, role-based access control (RBAC), and secure Stripe payment integration.",
    image: "/assetverse_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://assets-pro-ca84b.web.app/",
    technologies: ["React", "Firebase", "Node.js", "Stripe API", "Tailwind CSS"],
  },
  {
    id: "12",
    title: "ElectroPay Dashboard",
    description: "A digital utility billing platform that streamlines electricity bill management with real-time tracking, historical data visualization, and a seamless animated UI.",
    image: "/electricity_bill_mockup.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: "https://electricity-bills-225bf.web.app/",
    technologies: ["React", "Framer Motion", "Node.js", "MongoDB", "MUI/Tailwind"],
  },
  {
    id: "13",
    title: "Burger Shot",
    description: "A high-performance, responsive fast-food landing page built with raw HTML and optimized JavaScript, focusing on pixel-perfect UI and smooth scrolling.",
    image: "/burger_shop_mockup.png",
    githubLink: "https://github.com/rayhan309/Burgur-Shop",
    liveLink: "https://rayhan309.github.io/Burgur-Shop/",
    technologies: ["HTML5", "Tailwind CSS", "JavaScript", "FontAwesome"],
  },
  {
    id: "14",
    title: "AI Autonomous Agent",
    description: "A Python-based AI agent designed for automated task execution and data analysis.",
    image: "/ai_agent_preview.png",
    githubLink: "https://github.com/rayhan309",
    liveLink: null, // No live link
    status: "Private/Local Tool",
    technologies: ["Python", "OpenAI API", "LangChain"],
  }
];